# vim: syntax=python:shiftwidth=4:expandtab:tabstop=4:softtabstop=4

def options(opt):
    pass

def configure(cnf):
    pass

def build(bld):
    testing_env = bld.env.derive()
    testing_env.append_value('DFLAGS', bld.env['DFLAGS_UNIT_TESTING'])
    testing_env.append_value('DFLAGS', bld.env['DFLAGS_DEBUG'])
    
    # you can choose to not include the entire source directory; sometimes this
    # is necessary to avoid causing multiple definitions of 'main' in certain
    # projects.
    sources = bld.path.find_dir('..').find_dir('src').ant_glob('**/*.d')
    
    # this bit compiles each individual source file for the purpose of
    # unit testing.
    i = 0
    for s in sources:
        kosher_s = str(s).replace('.', '_')
        bld(
            features = 'd dprogram test',
            source=[s, 'test_main.d'],
            target=kosher_s+'_'+str(i),
            use=[], # Place all your libraries here
            env = testing_env
        )
        i += 1

