# vim: syntax=python:

def options(opt):
	pass

def configure(cnf):
	pass

def build(bld):
	testing_env = bld.env.derive()
	testing_env.append_value('DFLAGS', bld.env['DFLAGS_UNIT_TESTING'])
	testing_env.append_value('DFLAGS', bld.env['DFLAGS_DEBUG'])
	sources = bld.path.find_dir('..').find_dir('src').ant_glob('**/*.d')
	
	# this bit depends on the linker having C++ capabilities (which most have),
	# namely because there are N (identical) definitions flying around and
	# the linker needs to scrap N-1 of them.
	i = 0
	for s in sources:
		kosher_s = str(s).replace('.', '_')
		bld(
			features = 'd dprogram test',
			source=[s, 'test_main.d'],
			target=kosher_s+'_'+str(i),
			use=[], # Place all your libraries here
			env = testing_env
		)
		i += 1

