# vim: syntax=python:shiftwidth=4:expandtab:tabstop=4:softtabstop=4

def options(opt):
    pass
    # opt.recurse('your folder here')

def configure(cnf):
    pass
    # cnf.recurse('your folder here')

def build(bld):
    pass
    # bld.recurse('your folder here')

